<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default Suite" duration-ms="49" started-at="2018-10-22T07:15:33Z" finished-at="2018-10-22T07:15:33Z">
    <groups>
    </groups>
    <test name="TestNGTest-008ded8b-8c94-47f3-8c9a-ba618a9cf830" duration-ms="49" started-at="2018-10-22T07:15:33Z" finished-at="2018-10-22T07:15:33Z">
      <class name="com.function.TestHelloWorld">
        <test-method status="FAIL" signature="failtest()[pri:0, instance:com.function.TestHelloWorld@4d50efb8]" name="failtest" duration-ms="8" started-at="2018-10-22T07:15:33Z" finished-at="2018-10-22T07:15:33Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at com.function.TestHelloWorld.failtest(TestHelloWorld.java:15)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.microsoft.java.test.runner.testng.TestNGRunner.run(TestNGRunner.java:29)
at com.microsoft.java.test.runner.testng.TestNGLauncher.execute(TestNGLauncher.java:29)
at com.microsoft.java.test.runner.Launcher.execute(Launcher.java:55)
at com.microsoft.java.test.runner.Launcher.main(Launcher.java:38)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failtest -->
        <test-method status="PASS" signature="testEmailGenerator()[pri:0, instance:com.function.TestHelloWorld@4d50efb8]" name="testEmailGenerator" duration-ms="1" started-at="2018-10-22T07:15:33Z" finished-at="2018-10-22T07:15:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testEmailGenerator -->
      </class> <!-- com.function.TestHelloWorld -->
    </test> <!-- TestNGTest-008ded8b-8c94-47f3-8c9a-ba618a9cf830 -->
  </suite> <!-- Default Suite -->
</testng-results>
